In [2]:
import os
os.environ["USE_TF"]="0"
from sklearn.metrics import label_ranking_average_precision_score
from transformers import AutoTokenizer
import torch
from torch import nn
import pandas as pd
import tokenizer
import sklearn
import numpy as np
from torch.utils.data import DataLoader,Dataset
from sklearn.model_selection import train_test_split
from transformers import AutoModelForSequenceClassification
from transformers import Trainer,TrainingArguments

C:\Users\LOQ\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
x=pd.read_csv("IMDB Dataset.csv")
x.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
x=x.iloc[:10000]
x.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
x1=x["review"]
y=x["sentiment"]

In [6]:
from sklearn.preprocessing import LabelEncoder
lbl=LabelEncoder()
y=lbl.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 1], shape=(10000,))

In [7]:
tk=AutoTokenizer.from_pretrained("bert-base-uncased")

In [8]:
tk2=tk(x1.tolist(),padding=True,
       max_length=126,
       truncation=True,)

In [9]:
print(list(tk2.keys()))

['input_ids', 'token_type_ids', 'attention_mask']

In [10]:
print(tk2["input_ids"][:10])

[[101, 2028, 1997, 1996, 2060, 15814, 2038, 3855, 2008, 2044, 3666, 2074, 1015, 11472, 2792, 2017, 1005, 2222, 2022, 13322, 1012, 2027, 2024, 2157, 1010, 2004, 2023, 2003, 3599, 2054, 3047, 2007, 2033, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 2034, 2518, 2008, 4930, 2033, 2055, 11472, 2001, 2049, 24083, 1998, 4895, 10258, 2378, 8450, 5019, 1997, 4808, 1010, 2029, 2275, 1999, 2157, 2013, 1996, 2773, 2175, 1012, 3404, 2033, 1010, 2023, 2003, 2025, 1037, 2265, 2005, 1996, 8143, 18627, 2030, 5199, 3593, 1012, 2023, 2265, 8005, 2053, 17957, 2007, 12362, 2000, 5850, 1010, 3348, 2030, 4808, 1012, 2049, 2003, 13076, 1010, 1999, 1996, 4438, 2224, 1997, 1996, 2773, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2009, 2003, 2170, 11472, 102], [101, 1037, 6919, 2210, 2537, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 7467, 6028, 2003, 2200, 14477, 4757, 24270, 1011, 2200, 2214, 1011, 2051, 1011, 4035, 4827, 1998, 3957, 1037, 16334, 1010, 1998, 2823, 17964, 2075, 1010, 3168, 1997, 15650, 2000, 1996, 2972, 3538, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 5889, 2024, 5186, 2092, 4217, 1011, 2745, 20682, 2025, 2069, 1000, 2038, 2288, 2035, 1996, 11508, 2072, 1000, 2021, 2002, 2038, 2035, 1996, 5755, 2091, 6986, 2205, 999, 2017, 2064, 5621, 2156, 1996, 25180, 3238, 9260, 8546, 2011, 1996, 7604, 2000, 3766, 1005, 9708, 10445, 1010, 2025, 2069, 2003, 2009, 2092, 4276, 1996, 3666, 2021, 2009, 2003, 1037, 27547, 2135, 2517, 1998, 2864, 3538, 1012, 1037, 3040, 3993, 102], [101, 1045, 2245, 2023, 2001, 1037, 6919, 2126, 2000, 5247, 2051, 2006, 1037, 2205, 2980, 2621, 5353, 1010, 3564, 1999, 1996, 2250, 22442, 4258, 1998, 3666, 1037, 2422, 1011, 18627, 4038, 1012, 1996, 5436, 2003, 21934, 24759, 6553, 1010, 2021, 1996, 7982, 2003, 25591, 1998, 1996, 3494, 2024, 5622, 2912, 3468, 1006, 2130, 1996, 2092, 7852, 6878, 7642, 6359, 1007, 1012, 2096, 2070, 2089, 2022, 9364, 2043, 2027, 5382, 2023, 2003, 2025, 2674, 2391, 1016, 1024, 3891, 13449, 1010, 1045, 2245, 2009, 2001, 6947, 2008, 13703, 5297, 2003, 2145, 3929, 1999, 2491, 1997, 1996, 2806, 2116, 1997, 2149, 2031, 4961, 2000, 2293, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2023, 2001, 1996, 2087, 1045, 1005, 1040, 4191, 2012, 2028, 1997, 13703, 1005, 1055, 102], [101, 10468, 2045, 1005, 1055, 1037, 2155, 2073, 1037, 2210, 2879, 1006, 5180, 1007, 6732, 2045, 1005, 1055, 1037, 11798, 1999, 2010, 9346, 1004, 2010, 3008, 2024, 3554, 2035, 1996, 2051, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2023, 3185, 2003, 12430, 2084, 1037, 7815, 3850, 1012, 1012, 1012, 1998, 3402, 1010, 5180, 7288, 2000, 2468, 8223, 5092, 1998, 3102, 1996, 11798, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 7929, 1010, 2034, 1997, 2035, 2043, 2017, 1005, 2128, 2183, 2000, 2191, 1037, 2143, 2017, 2442, 5630, 2065, 2049, 1037, 10874, 2030, 1037, 3689, 999, 2004, 1037, 3689, 1996, 3185, 2003, 3422, 3085, 1012, 3008, 2024, 4487, 14550, 6129, 1004, 9177, 2066, 1999, 2613, 2166, 1012, 1998, 2059, 2057, 2031, 5180, 2007, 102], [101, 9004, 3334, 4717, 7416, 1005, 1055, 1000, 2293, 1999, 1996, 2051, 1997, 2769, 1000, 2003, 1037, 17453, 14726, 2143, 2000, 3422, 1012, 2720, 1012, 4717, 7416, 4107, 2149, 1037, 14954, 6533, 2055, 2529, 4262, 1012, 2023, 2003, 1037, 3185, 2008, 3849, 2000, 2022, 4129, 2149, 2054, 2769, 1010, 2373, 1998, 3112, 2079, 2000, 2111, 1999, 1996, 2367, 8146, 2057, 8087, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2023, 2108, 1037, 8386, 2006, 1996, 4300, 8040, 7295, 8838, 3917, 1005, 1055, 2377, 2055, 1996, 2168, 4323, 1010, 1996, 2472, 15210, 1996, 2895, 2000, 1996, 2556, 2051, 2047, 2259, 2073, 2035, 2122, 2367, 3494, 3113, 1998, 7532, 1012, 2169, 2028, 2003, 4198, 1999, 2028, 2126, 1010, 2030, 2178, 2000, 1996, 2279, 2711, 1010, 2021, 102], [101, 2763, 2026, 2035, 1011, 2051, 5440, 3185, 1010, 1037, 2466, 1997, 2969, 24913, 1010, 8688, 1998, 12276, 2000, 1037, 7015, 3426, 1010, 2021, 2009, 1005, 1055, 2025, 25250, 2100, 2030, 11771, 1012, 2009, 2074, 2196, 4152, 2214, 1010, 2750, 2026, 2383, 2464, 2009, 2070, 2321, 2030, 2062, 2335, 1999, 1996, 2197, 2423, 2086, 1012, 2703, 23739, 1005, 2836, 7545, 4000, 2000, 2026, 2159, 1010, 1998, 6655, 2618, 4482, 1010, 1999, 2028, 1997, 2014, 2200, 2261, 5621, 13026, 4395, 1010, 2003, 1037, 12208, 1012, 1996, 4268, 2024, 1010, 2004, 13055, 2758, 1010, 2062, 2066, 1000, 5102, 1011, 2039, 3054, 18150, 2015, 1000, 2084, 2336, 1010, 2021, 2008, 2069, 3084, 2068, 2062, 4569, 2000, 3422, 1012, 1998, 1996, 2388, 1005, 1055, 4030, 16936, 2000, 2054, 1005, 102], [101, 1045, 2469, 2052, 2066, 2000, 2156, 1037, 15218, 1997, 1037, 2039, 6052, 2712, 17157, 2102, 2186, 2007, 1996, 6627, 2027, 2031, 2651, 2009, 2052, 3288, 2067, 1996, 4845, 8277, 1999, 2033, 1012, 1045, 3473, 2039, 2006, 2304, 1998, 2317, 2694, 1998, 2712, 17157, 2102, 2007, 4409, 5302, 3489, 2020, 2026, 5394, 1005, 1055, 2296, 2733, 1012, 2017, 2031, 2026, 3789, 2005, 1037, 12845, 1997, 1037, 2047, 2712, 5690, 1012, 2057, 2342, 1037, 2689, 1997, 6393, 1999, 2694, 1998, 2023, 2052, 2147, 2005, 1037, 2088, 1997, 2104, 2300, 6172, 1012, 2821, 2011, 1996, 2126, 4067, 2017, 2005, 2019, 13307, 2066, 2023, 2000, 3193, 2116, 21386, 2015, 2055, 2694, 1998, 1996, 2116, 5691, 1012, 2061, 2151, 15589, 2126, 1045, 2903, 1045, 1005, 2310, 2288, 2054, 1045, 102], [101, 2023, 2265, 2001, 2019, 6429, 1010, 4840, 1004, 9525, 2801, 1999, 1996, 3963, 1005, 1055, 2043, 2009, 2034, 4836, 1012, 1996, 2034, 1021, 2030, 1022, 2086, 2020, 8235, 1010, 2021, 2477, 3333, 2125, 2044, 2008, 1012, 2011, 2901, 1010, 1996, 2265, 2001, 2025, 2428, 6057, 4902, 1010, 1998, 2009, 1005, 1055, 2506, 2049, 6689, 2582, 2000, 1996, 3143, 5949, 1997, 2051, 2009, 2003, 2651, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2009, 1005, 1055, 5621, 29591, 3993, 2129, 2521, 2023, 2265, 2038, 5357, 1012, 1996, 3015, 2003, 16267, 2919, 1010, 1996, 4616, 2024, 2471, 2004, 2919, 1011, 2065, 2025, 2005, 1996, 19499, 14036, 24501, 23270, 2063, 1997, 1996, 4113, 1011, 6184, 1010, 2023, 2265, 2763, 2876, 1005, 1056, 2145, 2022, 2006, 1996, 102], [101, 6628, 2011, 1996, 3893, 7928, 2055, 2023, 2143, 2006, 2182, 1045, 2001, 2559, 2830, 2000, 3666, 2023, 2143, 1012, 2919, 6707, 1012, 1045, 1005, 2310, 2464, 20317, 1009, 3152, 1998, 2023, 2003, 5621, 2028, 1997, 1996, 5409, 1997, 2068, 1011, 2009, 1005, 1055, 9643, 1999, 2471, 2296, 2126, 1024, 9260, 1010, 15732, 1010, 9994, 1010, 1005, 3772, 1010, 1005, 6050, 1006, 1996, 2143, 1005, 1055, 2069, 2299, 1011, 1037, 20342, 2406, 8694, 1011, 2003, 2209, 2053, 2625, 2084, 2176, 2335, 1007, 1012, 1996, 2143, 3504, 10036, 1998, 11808, 1998, 2003, 11771, 1999, 1996, 6034, 1012, 6524, 2031, 1045, 2042, 2061, 3407, 2000, 2156, 1996, 2203, 6495, 1997, 1037, 2143, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 2069, 2518, 2008, 16263, 2033, 102], [101, 2065, 2017, 2066, 2434, 9535, 16255, 8450, 7239, 2017, 2097, 2066, 2023, 3185, 1012, 2065, 2017, 2024, 2402, 2030, 2214, 2059, 2017, 2097, 2293, 2023, 3185, 1010, 3109, 2130, 2026, 3566, 4669, 2009, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2307, 3409, 999, 999, 999, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [11]:
x_train,x_temp,y_train,y_temp=train_test_split(x1,y,test_size=0.30, random_state=42,stratify=y)
x_val,x_test,y_val,y_test=train_test_split(x_temp,y_temp,test_size=0.5,random_state=42,stratify=y_temp)

print('train:',len(x_train),'val:',len(x_val),'test:',len(x_test))

train: 7000 val: 1500 test: 1500

In [12]:
model=AutoModelForSequenceClassification.from_pretrained("bert-base-uncased",num_labels=2,cache_dir="./bert_model")
tk_train=tk(x_train.tolist(),padding=True, truncation=True, max_length=126)
tk_val=tk(x_val.tolist(),padding=True, truncation=True, max_length=126)
tk_test=tk(x_test.tolist(),padding=True, truncation=True, max_length=126)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [13]:
class SentimentDataset(Dataset):
    def __init__(self,encoding,labels):
        self.encoding=encoding
        self.labels=labels
    def __len__(self):
        return len(self.labels)
    def __getitem__(self,idx):
         itm={key:torch.tensor(val[idx])for key,val in self.encoding.items()}
         itm["labels"]=torch.tensor(self.labels[idx])
         return itm

train_s=SentimentDataset(tk_train,y_train.tolist())
val_s=SentimentDataset(tk_val,y_val.tolist())
test_s=SentimentDataset(tk_test,y_test.tolist())

In [15]:
dev=torch.device("cuda")
model=model.to(dev)

ld=TrainingArguments(
    output_dir="./bert_model",
    num_train_epochs=1,
    gradient_accumulation_steps=1,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    save_strategy='epoch',
    eval_strategy='epoch',
    logging_steps=30,
    load_best_model_at_end=True,
    metric_for_best_model='eval_loss',
    greater_is_better=False,
    learning_rate=2e-5,
    weight_decay=0.01,
    save_total_limit=1,
    fp16=True,

)
tra=Trainer(
    model=model,
    args=ld,
    train_dataset=train_s,
    eval_dataset=val_s,
)

In [16]:
tra.train()

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.90it/s]
[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=1000, training_loss=0.38363722944259643, metrics={'train_runtime': 149.065, 'train_samples_per_second': 53.668, 'train_steps_per_second': 6.708, 'total_flos': 517999890240000.0, 'train_loss': 0.38363722944259643, 'epoch': 1.0})

In [18]:
tra.save_model("./english_sentiment_analysis")
tk.save_pretrained("./english_sentiment_analysis")

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s]

('./english_sentiment_analysis\\tokenizer_config.json',
 './english_sentiment_analysis\\tokenizer.json')

In [23]:
txt="yess,My mood is really good this song is really amazing"
inp=tk(txt,return_tensors="pt",truncation=True,max_length=126).to(dev)
model.eval()
with torch.no_grad():
    out=model(**inp)
    pr=torch.argmax(out.logits,dim=1).item()
lbl={1:"positive",0:"negative"}
print(lbl[pr])

positive

In [24]:
txt2="This is really bad it makes me feel bad."
inp2=tk(txt2,return_tensors="pt",truncation=True,max_length=126).to(dev)
model.eval()
with torch.no_grad():
    out2=model(**inp2)
    pr2=torch.argmax(out2.logits,dim=1).item()
lbl2={1:"positive",0:"negative"}
print(lbl2[pr2])

negative

In [25]:
txt3="I don't feel good about this matter; it really upset me."
inp3=tk(txt3,return_tensors="pt",truncation=True,max_length=126).to(dev)
model.eval()
with torch.no_grad():
    out3=model(**inp3)
    pr3=torch.argmax(out3.logits,dim=1).item()
lbl3={1:"positive",0:"negative"}
print(lbl3[pr3])

negative

In [27]:
txt4="This is amazing!!!"
inp4=tk(txt4,return_tensors="pt",truncation=True,max_length=126).to(dev)
model.eval()
with torch.no_grad():
    out4=model(**inp4)
    pr4=torch.argmax(out4.logits,dim=1).item()
lbl4={1:"positive",0:"negative"}
print(lbl4[pr4])

positive

In [34]:
from sklearn.metrics import classification_report
pred_A=[]
model.eval()
with torch.no_grad():
    for batch  in DataLoader(test_s, batch_size=16, shuffle=False):
        inpu={k:v.to(dev) for k,v in batch.items() if k!='labels'}
        outp=model(**inpu)
        pred_i=torch.argmax(outp.logits,dim=1)
        pred_A.extend(pred_i.cpu().tolist())
print(classification_report(y_test.tolist(),pred_A,target_names=["positive","negative"]))

              precision    recall  f1-score   support

    positive       0.90      0.85      0.88       996
    negative       0.86      0.91      0.88      1004

    accuracy                           0.88      2000
   macro avg       0.88      0.88      0.88      2000
weighted avg       0.88      0.88      0.88      2000