In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dropout,Dense
from tensorflow.keras.models  import Sequential
import os
import sklearn as sk
from sklearn.preprocessing import LabelEncoder

In [14]:
data=pd.read_csv("HPLC data.csv")
data.head()

,Sl No,Age,Gender,Religion,Present District,HbA0,HbA2,HbF,S-Window,Unknown,RBC,HB,MCV,MCH,MCHC,RDWcv,Weekness,Jaundice,Diagnosis
0,1,14 Yrs 11 month,Female,Hinduism,Howrah,86.2,2.9,0.3,0.0,0.0,4.81,13.2,86.7,28.8,33.0,13.8,No,No,Normal
1,2,16 Yrs 0 month,Female,Hinduism,Kolkata,86.4,4.8,0.4,0.0,0.0,4.18,10.9,78.9,26.1,33.0,14.6,No,No,Beta Thalassaemia carrier
2,3,16 Yrs 2 month,Male,Hinduism,Hooghly,87.3,3.2,0.5,0.0,0.0,5.31,13.6,87.0,25.6,29.4,13.7,No,No,Normal
3,4,21 Yrs 0 month,Female,Hinduism,South 24-Parganas,87.9,2.8,0.2,0.0,0.0,4.64,11.5,78.7,44.8,31.5,14.5,No,No,Normal
4,5,35 Yrs 3 month,Male,Hinduism,Midnapore (East),84.3,2.8,0.2,0.0,0.0,5.50,14.0,69.7,21.5,30.9,16.5,No,No,Normal

In [15]:
data=data.drop(columns=["Unknown","Sl No","Religion","Present District"])
data.head()

,Age,Gender,HbA0,HbA2,HbF,S-Window,RBC,HB,MCV,MCH,MCHC,RDWcv,Weekness,Jaundice,Diagnosis
0,14 Yrs 11 month,Female,86.2,2.9,0.3,0.0,4.81,13.2,86.7,28.8,33.0,13.8,No,No,Normal
1,16 Yrs 0 month,Female,86.4,4.8,0.4,0.0,4.18,10.9,78.9,26.1,33.0,14.6,No,No,Beta Thalassaemia carrier
2,16 Yrs 2 month,Male,87.3,3.2,0.5,0.0,5.31,13.6,87.0,25.6,29.4,13.7,No,No,Normal
3,21 Yrs 0 month,Female,87.9,2.8,0.2,0.0,4.64,11.5,78.7,44.8,31.5,14.5,No,No,Normal
4,35 Yrs 3 month,Male,84.3,2.8,0.2,0.0,5.50,14.0,69.7,21.5,30.9,16.5,No,No,Normal

In [16]:
lb=LabelEncoder()
data["Diagnosis"]=data["Diagnosis"].str.strip()
data["Diagnosis"]=lb.fit_transform(data["Diagnosis"])

print(lb.classes_)

['Beta Thalassaemia carrier' 'Beta Thalassaemia major'
 'Beta trait with high foetal haemoglobin' 'Delta beta carrier'
 'HPFH trait' 'HbD carrier' 'HbD disease' 'HbE carrier' 'HbE disease'
 'HbE-Beta Thalassaemia' 'HbS carrier' 'HbS-Beta Thalassaemia' 'Normal']