In [1]:
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras.layers import Conv2D,Dense,Dropout,Input,LSTM,GRU
import pandas as pd 
import numpy as np

In [2]:
data=pd.read_csv("usdt-usd-max.csv")
data[:10]

                snapped_at     price  market_cap  total_volume
0  2015-02-25 00:00:00 UTC  1.210160    304476.0           5.0
1  2015-03-02 00:00:00 UTC  0.572521    144046.0           2.0
2  2015-03-06 00:00:00 UTC  1.000000    251600.0          50.0
3  2015-03-07 00:00:00 UTC  1.000000    251600.0       58196.0
4  2015-03-08 00:00:00 UTC  1.000000    251600.0          31.0
5  2015-03-09 00:00:00 UTC  1.000000    251600.0         137.0
6  2015-03-10 00:00:00 UTC  1.000000    251600.0       50006.0
7  2015-03-11 00:00:00 UTC  1.000000    251600.0          46.0
8  2015-03-12 00:00:00 UTC  1.000000    251600.0       80421.0
9  2015-03-13 00:00:00 UTC  1.000000    251600.0          75.0

In [3]:
data2=pd.read_excel("tether.xlsx")
data2

C:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,timeOpen,timeClose,timeHigh,timeLow,priceOpen,priceHigh,priceLow,priceClose,volume
0,1770033600000,1770119999999,1770053820000,1770057780000,0.999001,1.001027,0.997636,0.999132,1.779279e+11
1,1769947200000,1770033599999,1769985240000,1770018480000,0.998866,1.000378,0.998374,0.999110,1.164217e+11
2,1769860800000,1769947199999,1769912820000,1769928300000,0.998428,1.002031,0.996447,0.998891,1.505837e+11
3,1769774400000,1769860799999,1769830440000,1769780640000,0.998352,1.000805,0.997380,0.998488,1.418299e+11
4,1769688000000,1769774399999,1769697180000,1769763240000,0.998908,0.999463,0.997865,0.998339,1.255133e+11
...,...,...,...,...,...,...,...,...,...
2694,1535284800000,1535371199999,1535294040000,1535335141000,1.003210,1.007950,0.997750,0.999227,1.946530e+09
2695,1535198400000,1535284799999,1535256543000,1535251441000,0.998537,1.003820,0.995268,1.001000,1.958700e+09
2696,1535112000000,1535198399999,1535165041000,1535180342000,0.998429,1.008960,0.994293,1.001780,2.850500e+09
2697,1535025600000,1535111999999,1535059742000,1535076544000,1.001350,1.004250,0.993635,0.998976,2.392970e+09
2698,1534939200000,1535025599999,1535011740000,1534943342000,1.000490,1.011780,0.981115,1.000350,3.325510e+09

In [ ]:
time_step=30
d1=['price','return','ma_5','buy']
d2 = ['priceClose', 'return', 'hl_spread', 'ma_5', 'ma_10', 'volume', 'buy']

In [ ]:
k=10
threshold=0.01
future_price=data2['priceClose'].shift(-k)
data2['buy']=(future_price>data2['priceClose']*(1+threshold)).astype(int)

In [ ]:
def normalize(df):
    return (df-df.min())/(df.max()-df.min())

In [ ]:
data1_scaled=normalize(data[d1])
data2_scaled=normalize(data2[d2])

In [ ]:
def make_sequence(df,time_step):
    seq=[]
    for i in range(time_step,len(df)):
        seq.append(df[i-time_step:i].values)
    return np.array(seq)

In [ ]:
x1_seq=make_sequence(data1_scaled,time_step)
x2_seq=make_sequence(data2_scaled,time_step)

In [13]:
future=data['price'].shift(-10)
data['buy']=(future>data['price']*1.01).astype(int)

In [ ]:
data['return']=data['price'].pct_change()
data['ma_5']=data['price'].rolling(5).mean()
data=data.dropna()

In [51]:
d1=['price','return','ma_5','buy']

In [59]:
model=Sequential()

model.add(LSTM(100,return_sequences=True,input_shape=(time_step,n_features)))
model.add(Dropout(0.3))
model.add(LSTM(42,return_sequences=True))
model.add(LSTM(21,return_sequences=True))
model.add(Dense(1,activation='sigmoid'))
out=model(output)

c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

NameError: name 'output' is not defined

In [29]:
data2=pd.read_excel("tether.xlsx")
data2

c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,timeOpen,timeClose,timeHigh,timeLow,priceOpen,priceHigh,priceLow,priceClose,volume
0,1770033600000,1770119999999,1770053820000,1770057780000,0.999001,1.001027,0.997636,0.999132,1.779279e+11
1,1769947200000,1770033599999,1769985240000,1770018480000,0.998866,1.000378,0.998374,0.999110,1.164217e+11
2,1769860800000,1769947199999,1769912820000,1769928300000,0.998428,1.002031,0.996447,0.998891,1.505837e+11
3,1769774400000,1769860799999,1769830440000,1769780640000,0.998352,1.000805,0.997380,0.998488,1.418299e+11
4,1769688000000,1769774399999,1769697180000,1769763240000,0.998908,0.999463,0.997865,0.998339,1.255133e+11
...,...,...,...,...,...,...,...,...,...
2694,1535284800000,1535371199999,1535294040000,1535335141000,1.003210,1.007950,0.997750,0.999227,1.946530e+09
2695,1535198400000,1535284799999,1535256543000,1535251441000,0.998537,1.003820,0.995268,1.001000,1.958700e+09
2696,1535112000000,1535198399999,1535165041000,1535180342000,0.998429,1.008960,0.994293,1.001780,2.850500e+09
2697,1535025600000,1535111999999,1535059742000,1535076544000,1.001350,1.004250,0.993635,0.998976,2.392970e+09
2698,1534939200000,1535025599999,1535011740000,1534943342000,1.000490,1.011780,0.981115,1.000350,3.325510e+09

In [37]:
k=10
threshold=0.01
future_price=data2['priceClose'].shift(-k)
data2['buy']=(future_price>data2['priceClose']*(1+threshold)).astype(int)

In [38]:
data2['return']=data2['priceClose'].pct_change()
data2['h1_spread']=data2['priceHigh']-data2['priceLow']
data2['ma_5']=data2['priceClose'].rolling(5).mean()
data2['ma_10']=data2['priceClose'].rolling(10).mean()

In [52]:
d2 = ['priceClose', 'return', 'hl_spread', 'ma_5', 'ma_10', 'volume', 'buy']

In [54]:
n_features = len(d2)
n_features

7

In [45]:
time_step=30

In [ ]:
model=Sequential()

model.add(LSTM(64,return_sequences=True,input_shape=(time_step,n_features)))
model.add(Dropout(0.3))
model.add(LSTM(120,return_sequences=True))
model.add(LSTM(77,return_sequences=True))
model.add(Dense(1,activation='sigmoid'))

c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)